global using GameStation.Data;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using GameStation.Services;
global using GameStation.Models;
global using GameStation.ViewModels;
global using GameStation.Settings;